#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

users = {}
channels = {}

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()

def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    
    # add o que foi recebido no buffer da conn
    conexao.buffer += dados
    while b'\r\n' in conexao.buffer: 
        # enquanto ainda estiver '\r\n' no buffer,
        # ele separa a msg fragmentada, ate a primeira ocorrencia, 
        mensagem, conexao.buffer = conexao.buffer.split(b'\r\n', 1)

        if mensagem.startswith(b'PING'):
            partes = mensagem.split(b' ', 1)
            conexao.enviar(b':server PONG server :' + partes[1] + b'\r\n')
        
        elif mensagem.startswith(b'NICK'):
            _, nick = mensagem.split(b' ', 1)
            nick_lower = nick.lower()
            
            if not validar_nome(nick):
                conexao.enviar(b':server 432 '+ conexao.nick + b' ' + nick + b' :Erroneous nickname\r\n')
           
            elif nick_lower in users:
                conexao.enviar(b':server 433 '+ conexao.nick + b' ' + nick + b' :Nickname is already in use\r\n')  
            else:
                old_nick = conexao.nick
                conexao.nick = nick
                users[nick_lower] = conexao
                
                if old_nick == b'*':
                    conexao.enviar(b':server 001 ' + conexao.nick + b' :Welcome\r\n')
                    conexao.enviar(b':server 422 ' + conexao.nick + b' :MOTD File is missing\r\n')
                else:
                    del users[old_nick.lower()]
                    conexao.enviar(b':' + old_nick + b' NICK ' + nick + b'\r\n')
        
        elif mensagem.startswith(b'PRIVMSG'):
            _, dest, msg = mensagem.split(b' ', 2)
            dest_lower = dest.lower()
            
            if dest.startswith(b'#'):
                if dest_lower in channels:
                    for user in channels[dest_lower]:
                        if user != conexao:
                            user.enviar(b':' + conexao.nick + b' PRIVMSG ' + dest + b' ' + msg + b'\r\n')
            
            if dest_lower in users:
                conn_dest = users[dest_lower]
                conn_dest.enviar(b':' + conexao.nick + b' PRIVMSG ' + dest + b' ' + msg + b'\r\n')
        
        elif mensagem.startswith(b'JOIN'):
            _, channel = mensagem.split(b' ', 1)
            
            if not channel.startswith(b'#') or not validar_nome(channel[1:]):
                conexao.enviar(b':server 403 ' + channel + b' :No such channel\r\n')
            else:
                channel_lower = channel.lower()
                
                # verifica se o canal esta na lista de canais, caso nao, adiciona-o
                if not channel_lower in channels:
                    channels[channel_lower] = []
                    
                # verifica se o userX esta na lista de users do canal, caso nao, adiciona-o
                if not conexao in channels[channel_lower]:
                    channels[channel_lower].append(conexao)
                
                # envia para todos os users do canal que o userX entrou
                for user in channels[channel_lower]:
                    user.enviar(b':' + conexao.nick + b' JOIN :' + channel + b'\r\n')
                    
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.nick = b'*'
    
    # buffer para salvar as mensagens/residuos
    conexao.buffer = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
