#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

users = {}
channels = {}

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    users_to_send = set()
    
    # Busca todas as conexoes em um canal
    for channel in channels.values():
        
        # Se a conexao que vai sair estiver no canal, entra na condicao
        if conexao in channel:
            
            # Itera as conexoes presentes no canal e adciona cada uma
            # em um conjunto para que nao tenha repeticoes
            for conn in channel:
                if conexao != conn:
                    users_to_send.add(conn)
            channel.remove(conexao)   

    for user in users_to_send:
        user.enviar(b':' + conexao.nick + b' QUIT :Connection closed\r\n')

    print(conexao, 'conexão fechada')
    nick_lower = conexao.nick.lower()
    if nick_lower in users:
        del users[nick_lower]
    conexao.fechar()

def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    
    # add o que foi recebido no buffer da conn
    conexao.buffer += dados
    while b'\r\n' in conexao.buffer: 
        # enquanto ainda estiver '\r\n' no buffer,
        # ele separa a msg fragmentada, ate a primeira ocorrencia, 
        mensagem, conexao.buffer = conexao.buffer.split(b'\r\n', 1)

        if mensagem.startswith(b'PING'):
            partes = mensagem.split(b' ', 1)
            conexao.enviar(b':server PONG server :' + partes[1] + b'\r\n')
        
        elif mensagem.startswith(b'NICK'):
            _, nick = mensagem.split(b' ', 1)
            nick_lower = nick.lower()
            
            if not validar_nome(nick):
                conexao.enviar(b':server 432 '+ conexao.nick + b' ' + nick + b' :Erroneous nickname\r\n')
           
            elif nick_lower in users:
                conexao.enviar(b':server 433 '+ conexao.nick + b' ' + nick + b' :Nickname is already in use\r\n')  
            else:
                old_nick = conexao.nick
                conexao.nick = nick
                users[nick_lower] = conexao
                
                if old_nick == b'*':
                    conexao.enviar(b':server 001 ' + conexao.nick + b' :Welcome\r\n')
                    conexao.enviar(b':server 422 ' + conexao.nick + b' :MOTD File is missing\r\n')
                else:
                    del users[old_nick.lower()]
                    conexao.enviar(b':' + old_nick + b' NICK ' + nick + b'\r\n')
        
        elif mensagem.startswith(b'PRIVMSG'):
            _, dest, msg = mensagem.split(b' ', 2)
            dest_lower = dest.lower()
            
            if dest.startswith(b'#'):
                if dest_lower in channels:
                    for user in channels[dest_lower]:
                        if user != conexao:
                            user.enviar(b':' + conexao.nick + b' PRIVMSG ' + dest + b' ' + msg + b'\r\n')
            
            if dest_lower in users:
                conn_dest = users[dest_lower]
                conn_dest.enviar(b':' + conexao.nick + b' PRIVMSG ' + dest + b' ' + msg + b'\r\n')
        
        elif mensagem.startswith(b'JOIN'):
            _, channel = mensagem.split(b' ', 1)
            
            if not channel.startswith(b'#') or not validar_nome(channel[1:]):
                conexao.enviar(b':server 403 ' + channel + b' :No such channel\r\n')
            else:
                channel_lower = channel.lower()
                
                # verifica se o canal esta na lista de canais, caso nao, adiciona-o
                if not channel_lower in channels:
                    channels[channel_lower] = []
                    
                # verifica se o userX esta na lista de users do canal, caso nao, adiciona-o
                if not conexao in channels[channel_lower]:
                    channels[channel_lower].append(conexao)
                
                users_in_channel = []
                
                # envia para todos os users do canal que o userX entrou
                for user in channels[channel_lower]:
                    users_in_channel.append(user.nick)
                    user.enviar(b':' + conexao.nick + b' JOIN :' + channel + b'\r\n')

                users_in_channel.sort()
                
                prefix = b':server 353 ' + conexao.nick + b' = ' + channel + b' :'
                curr_size = 0
                nicks_line = []
                available_size = 510 - len(prefix)                
                
                for nick in users_in_channel:
                    if curr_size + len(nick) + 1 > available_size and nicks_line:
                        msg = b" ".join(nicks_line)
                        conexao.enviar(prefix + msg + b'\r\n')
                       
                        curr_size = 0
                        nicks_line = []
                    
                    nicks_line.append(nick)
                    curr_size += len(nick) + 1
                
                if nicks_line:
                    msg = b" ".join(nicks_line)
                    conexao.enviar(prefix + msg + b'\r\n')
                    
                conexao.enviar(b':server 366 ' + conexao.nick + b' ' + channel + b' :End of /NAMES list.\r\n')
                
        elif mensagem.startswith(b'PART'):
            _, part = mensagem.split(b' ', 1)
            channel = part.split(b' ', 1)[0] 
            channel_lower = channel.lower()
            
            if channel_lower in channels and conexao in channels[channel_lower]:
                for user in channels[channel_lower]:
                    user.enviar(b':' + conexao.nick + b' PART ' + channel + b'\r\n')
                channels[channel_lower].remove(conexao)       
                     
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.nick = b'*'
    
    # buffer para salvar as mensagens/residuos
    conexao.buffer = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
