#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re

users = {}

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    
    # add o que foi recebido no buffer da conn
    conexao.buffer += dados
    while b'\r\n' in conexao.buffer: 
        # enquanto ainda estiver '\r\n' no buffer,
        # ele separa a msg fragmentada, ate a primeira ocorrencia, 
        mensagem, conexao.buffer = conexao.buffer.split(b'\r\n', 1)

        if mensagem.startswith(b'PING'):
            partes = mensagem.split(b' ', 1)
            conexao.enviar(b':server PONG server :' + partes[1] + b'\r\n')
        
        elif mensagem.startswith(b'NICK'):
            _, nick = mensagem.split(b' ', 1)
            nick_lower = nick.lower()
            
            if not validar_nome(nick):
                conexao.enviar(b':server 432 '+ conexao.nick + b' ' + nick + b' :Erroneous nickname\r\n')
           
            elif nick_lower in users:
                conexao.enviar(b':server 433 '+ conexao.nick + b' ' + nick + b' :Nickname is already in use\r\n')  
            else:
                old_nick = conexao.nick
                conexao.nick = nick
                users[nick_lower] = conexao
                
                if old_nick == b'*':
                    conexao.enviar(b':server 001 ' + conexao.nick + b' :Welcome\r\n')
                    conexao.enviar(b':server 422 ' + conexao.nick + b' :MOTD File is missing\r\n')
                else:
                    del users[old_nick.lower()]
                    conexao.enviar(b':' + old_nick + b' NICK ' + nick + b'\r\n')
        
        if mensagem.startswith(b'PRIVMSG'):
            _, dest, msg = mensagem.split(b' ', 2)
            
            if dest.lower() in users:
                conn_dest = users[dest.lower()]
                conn_dest.enviar(b':' + conexao.nick + b' PRIVMSG ' + dest + b' ' + msg + b'\r\n')
                
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.nick = b'*'
    
    # buffer para salvar as mensagens/residuos
    conexao.buffer = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
